FROM node:26-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY backend/package.json ./backend/
COPY frontend/package.json ./frontend/

RUN pnpm install

COPY backend ./backend

WORKDIR /app/backend

EXPOSE 5000

CMD ["pnpm", "dev"]